### ISSUE TITLE
Can't bind to 'value' since it isn't a known property of 'ngx-select-dropdown'.

### ISSUE THREAD

**Issue by baj9032** [manishjanky/ngx-select-dropdown#48]
I dig into below error. I am working with angular 4.0.0.

core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'ngx-select-dropdown'.
1. If 'ngx-select-dropdown' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'ngx-select-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ton>Categories</button>-->
            
            <ngx-select-dropdown [ERROR ->][(value)]="singleSelect" [config]="config" [options]="options"></ngx-select-dropdown>
            "): ng:///NewsModule/DesktopEventsComponent.html@42:33

**Comment by manishjanky** [comment]
Did you import SelecteDropdownModule in your AppModule?

**Comment by manishjanky** [comment]
Then this should not happen. Have you imported `FormsModule` as it requires that. Please check.

**Comment by baj9032** [comment]
@manishjanky : I already imported `FormsModule` in app.module.ts file.

**Comment by manishjanky** [comment]
thats strange because i just tested it works fine. PFB the link please try to validate according to the code on the link and let me know if you still face any issue.

https://stackblitz.com/edit/angular-crjqyw

**Comment by baj9032** [comment]
In angular 6 everything is working fine but when I tried to integrate this plugin into the angular4 application. It's give me error that I mentioned above.

**Comment by manishjanky** [comment]
Will it be possible for you create a demo of the code you have replicating the issue. Will see whats the problem.

**Comment by baj9032** [comment]
Actually no because my application is tightly coupled with dot net. anyway let me try something else.

**Comment by baj9032** [comment]
I got my answer from stack overflow. Stackoverflow question [Link](https://stackoverflow.com/questions/52166286/cant-bind-to-value-since-it-isnt-a-known-property-of-ngx-select-dropdown/52166735#52166735).
